# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
      - maven-build

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      working-directory: ./Grade_Predictor
      run: mvn -B clean compile package -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: grade-predictor-${{ github.run_number }}
        path: |
          ./Grade_Predictor/target/*.jar

    #- name: Publish to GitHub Packages Apache Maven
    #  working-directory: ./Grade_Predictor
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #     GITHUB_TOKEN: ${{ github.token }}
    # TESTING
